#!/bin/bash
gcc --version 2> /dev/null
if [$? -eq 0]; then
    gcc main.cpp -o main -vstdc++
    if [$? -eq 0]; then
        ./main
    else
        echo "Compile has failed. Fix the errors, and you can run."
    fi
else
    echo "Install build-essential to run"
fi