#!/bin/bash
gcc --version 2>&1 >/dev/null
if [ $? -eq 0 ]; then
    gcc main.cpp -o main -lstdc++
    if [ $? -eq 0 ]; then
        args=""
        for i in $*; do 
            args="${args}$i "
        done
        ./main $i $args
    else
        echo "Compile has failed. Fix the errors, and you can run."
    fi
else
    echo "Install build-essential to run"
fi