#!/bin/bash
gcc --version 2>&1 >/dev/null
if [ $? -eq 0 ]; then
        #gcc main.cpp -o main -lstdc++
        echo "If using Visual studio press F6 to build automatically"
    ./main
else
    echo "Install build-essential to run."
fi